import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./shercosta.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  keranjang,
}: Readonly<{
  children: React.ReactNode;
  keranjang: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
          <div>{children}</div>
          {keranjang}
        </div>
      </body>
    </html>
  );
}
