import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./shercosta.css";
import Providers from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  keranjang,
}: Readonly<{
  children: React.ReactNode;
  keranjang: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="main relative">
            <div>{children}</div>
            {keranjang}
          </div>
        </Providers>
      </body>
    </html>
  );
}
